FROM rockylinux:9
RUN dnf install -y freeipa-server freeipa-server-dns freeipa-client && dnf clean all
# Remove non-necessary systemd parts
RUN find /etc/systemd/system /usr/lib/systemd/system/{basic,multi-user,sysinit}.target.wants -type l -not -lname /dev/null -delete && systemctl mask systemd-logind.service && ln -s /usr/lib/systemd/system/dbus-broker.service /usr/lib/systemd/system/dbus.service
COPY entrypoint.service /etc/systemd/system/entrypoint.service
RUN systemctl enable entrypoint.service
COPY scripts/patch_hosts.sh /scripts/
ENTRYPOINT ["/usr/sbin/init"]
CMD ["--show-status=false"]
